// Auto-generated from: community.general.android_sdk
// DO NOT EDIT — regenerate with codegen

import { defineModule } from "@sensible-ts/core";

export interface AndroidSdkArgs {
  /** If this is set to V(true), the module attempts to accept license prompts generated by C(sdkmanager) during package installation. Otherwise, every license prompt is rejected. */
  accept_licenses?: boolean;
  /** Indicates what channel must C(sdkmanager) use for installation of packages. */
  channel?: "stable" | "beta" | "dev" | "canary";
  /** A name of an Android SDK package (for instance, V(build-tools;34.0.0)). */
  name?: string | string[];
  /** Provides path for an alternative directory to install Android SDK packages to. By default, all packages are installed to the directory where C(sdkmanager) is installed. */
  sdk_root?: string;
  /** Indicates the desired package(s) state. */
  state?: "present" | "absent" | "latest";
}

export interface AndroidSdkReturn {
  /** A list of packages that have been installed. */
  installed?: string | string[];
  /** A list of packages that have been removed. */
  removed?: string | string[];
}

export const android_sdk = defineModule<AndroidSdkArgs, AndroidSdkReturn>("community.general.android_sdk");
