// Auto-generated from: community.general.keycloak_userprofile
// DO NOT EDIT — regenerate with codegen

import { defineModule } from "@sensible-ts/core";

export interface KeycloakUserprofileArgs {
  /** OpenID Connect C(client_id) to authenticate to the API with. */
  auth_client_id?: string;
  /** Client Secret to use in conjunction with O(auth_client_id) (if required). */
  auth_client_secret?: string;
  /** URL to the Keycloak instance. */
  auth_keycloak_url: string;
  /** Password to authenticate for API access with. */
  auth_password?: string;
  /** Keycloak realm name to authenticate to for API access. */
  auth_realm?: string;
  /** Username to authenticate for API access with. */
  auth_username?: string;
  /** The configuration of the User Profile Provider. */
  config?: {
    kc_user_profile_config?: Record<string, unknown> | Record<string, unknown>[];
  };
  /** Controls the HTTP connections timeout period (in seconds) to Keycloak API. */
  connection_timeout?: number;
  /** Configures the HTTP User-Agent header. */
  http_agent?: string;
  /** The parent ID of the realm key. In practice the ID (name) of the realm. */
  parent_id: string;
  /** The name of the provider ID for the key (supported value is V(declarative-user-profile)). */
  provider_id?: "declarative-user-profile";
  /** Component type for User Profile (only supported value is V(org.keycloak.userprofile.UserProfileProvider)). */
  provider_type?: "org.keycloak.userprofile.UserProfileProvider";
  /** Authentication refresh token for Keycloak API. */
  refresh_token?: string;
  /** State of the User Profile provider. */
  state?: "present" | "absent";
  /** Authentication token for Keycloak API. */
  token?: string;
  /** Verify TLS certificates (do not disable this in production). */
  validate_certs?: boolean;
}

export interface KeycloakUserprofileReturn {
  /** The data returned by the Keycloak API. */
  data?: Record<string, unknown>;
  /** The output message generated by the module. */
  msg?: string;
}

export const keycloak_userprofile = defineModule<KeycloakUserprofileArgs, KeycloakUserprofileReturn>("community.general.keycloak_userprofile");
