// Auto-generated from: community.general.keycloak_realm
// DO NOT EDIT — regenerate with codegen

import { defineModule } from "@sensible-ts/core";

export interface KeycloakRealmArgs {
  /** The realm access code lifespan. */
  access_code_lifespan?: number;
  /** The realm access code lifespan login. */
  access_code_lifespan_login?: number;
  /** The realm access code lifespan user action. */
  access_code_lifespan_user_action?: number;
  /** The realm access token lifespan. */
  access_token_lifespan?: number;
  /** The realm access token lifespan for implicit flow. */
  access_token_lifespan_for_implicit_flow?: number;
  /** The realm account theme. */
  account_theme?: string;
  /** The realm action token generated by admin lifespan. */
  action_token_generated_by_admin_lifespan?: number;
  /** The realm action token generated by user lifespan. */
  action_token_generated_by_user_lifespan?: number;
  /** The realm admin events details enabled. */
  admin_events_details_enabled?: boolean;
  /** The realm admin events enabled. */
  admin_events_enabled?: boolean;
  /** The realm admin permissions enabled. */
  admin_permissions_enabled?: boolean;
  /** The realm admin theme. */
  admin_theme?: string;
  /** The realm attributes. */
  attributes?: Record<string, unknown>;
  /** OpenID Connect C(client_id) to authenticate to the API with. */
  auth_client_id?: string;
  /** Client Secret to use in conjunction with O(auth_client_id) (if required). */
  auth_client_secret?: string;
  /** URL to the Keycloak instance. */
  auth_keycloak_url: string;
  /** Password to authenticate for API access with. */
  auth_password?: string;
  /** Keycloak realm name to authenticate to for API access. */
  auth_realm?: string;
  /** Username to authenticate for API access with. */
  auth_username?: string;
  /** The realm browser flow. */
  browser_flow?: string;
  /** The realm browser security headers. */
  browser_security_headers?: Record<string, unknown>;
  /** The realm brute force protected. */
  brute_force_protected?: boolean;
  /** The realm brute force strategy. */
  brute_force_strategy?: "LINEAR" | "MULTIPLE";
  /** The realm client authentication flow. */
  client_authentication_flow?: string;
  /** All Clients inherit from this setting, time an offline session is allowed to be idle before it expires. */
  client_offline_session_idle_timeout?: number;
  /** All Clients inherit from this setting, max time before an offline session is expired regardless of activity. */
  client_offline_session_max_lifespan?: number;
  /** The realm client scope mappings. */
  client_scope_mappings?: Record<string, unknown>;
  /** All Clients inherit from this setting, time a session is allowed to be idle before it expires. */
  client_session_idle_timeout?: number;
  /** All Clients inherit from this setting, max time before a session is expired. */
  client_session_max_lifespan?: number;
  /** Controls the HTTP connections timeout period (in seconds) to Keycloak API. */
  connection_timeout?: number;
  /** The realm default default client scopes. */
  default_default_client_scopes?: string | string[];
  /** The realm default groups. */
  default_groups?: string | string[];
  /** The realm default locale. */
  default_locale?: string;
  /** The realm default optional client scopes. */
  default_optional_client_scopes?: string | string[];
  /** The realm default roles. */
  default_roles?: string | string[];
  /** The realm default signature algorithm. */
  default_signature_algorithm?: string;
  /** The realm direct grant flow. */
  direct_grant_flow?: string;
  /** The realm display name. */
  display_name?: string;
  /** The realm display name HTML. */
  display_name_html?: string;
  /** The realm docker authentication flow. */
  docker_authentication_flow?: string;
  /** The realm duplicate emails allowed option. */
  duplicate_emails_allowed?: boolean;
  /** The realm edit username allowed option. */
  edit_username_allowed?: boolean;
  /** The realm email theme. */
  email_theme?: string;
  /** The realm enabled option. */
  enabled?: boolean;
  /** The realm enabled event types. */
  enabled_event_types?: string | string[];
  /** Enables or disables login events for this realm. */
  events_enabled?: boolean;
  /** The realm events expiration. */
  events_expiration?: number;
  /** The realm events listeners. */
  events_listeners?: string | string[];
  /** The realm failure factor. */
  failure_factor?: number;
  /** Configures the HTTP User-Agent header. */
  http_agent?: string;
  /** The realm to create. */
  id?: string;
  /** The realm internationalization enabled option. */
  internationalization_enabled?: boolean;
  /** The realm login theme. */
  login_theme?: string;
  /** The realm login with email allowed option. */
  login_with_email_allowed?: boolean;
  /** The realm max delta time in seconds. */
  max_delta_time_seconds?: number;
  /** The realm max failure wait in seconds. */
  max_failure_wait_seconds?: number;
  /** The realm max temporary lockouts. */
  max_temporary_lockouts?: number;
  /** The realm minimum quick login wait in seconds. */
  minimum_quick_login_wait_seconds?: number;
  /** The realm not before. */
  not_before?: number;
  /** Max time before the device code and user code are expired. */
  oauth2_device_code_lifespan?: number;
  /** The minimum amount of time in seconds that the client should wait between polling requests to the token endpoint. */
  oauth2_device_polling_interval?: number;
  /** The realm offline session idle timeout. */
  offline_session_idle_timeout?: number;
  /** The realm offline session max lifespan. */
  offline_session_max_lifespan?: number;
  /** The realm offline session max lifespan enabled option. */
  offline_session_max_lifespan_enabled?: boolean;
  /** Enables support for experimental organization feature. */
  organizations_enabled?: boolean;
  /** The realm otp policy algorithm. */
  otp_policy_algorithm?: string;
  /** The realm otp policy digits. */
  otp_policy_digits?: number;
  /** The realm otp policy initial counter. */
  otp_policy_initial_counter?: number;
  /** The realm otp policy look ahead window. */
  otp_policy_look_ahead_window?: number;
  /** The realm otp policy period. */
  otp_policy_period?: number;
  /** The realm otp policy type. */
  otp_policy_type?: string;
  /** The realm otp supported applications. */
  otp_supported_applications?: string | string[];
  /** The realm password policy. */
  password_policy?: string;
  /** The realm permanent lockout. */
  permanent_lockout?: boolean;
  /** The realm quick login check in milliseconds. */
  quick_login_check_milli_seconds?: number;
  /** The realm name. */
  realm?: string;
  /** Authentication refresh token for Keycloak API. */
  refresh_token?: string;
  /** The realm refresh token max reuse. */
  refresh_token_max_reuse?: number;
  /** The realm registration allowed option. */
  registration_allowed?: boolean;
  /** The realm registration email as username option. */
  registration_email_as_username?: boolean;
  /** The realm registration flow. */
  registration_flow?: string;
  /** The realm remember me option. */
  remember_me?: boolean;
  /** The realm reset credentials flow. */
  reset_credentials_flow?: string;
  /** The realm reset password allowed option. */
  reset_password_allowed?: boolean;
  /** The realm revoke refresh token option. */
  revoke_refresh_token?: boolean;
  /** The realm smtp server. */
  smtp_server?: Record<string, unknown>;
  /** The realm ssl required option. */
  ssl_required?: "all" | "external" | "none";
  /** The realm sso session idle timeout. */
  sso_session_idle_timeout?: number;
  /** The realm sso session idle timeout remember me. */
  sso_session_idle_timeout_remember_me?: number;
  /** The realm sso session max lifespan. */
  sso_session_max_lifespan?: number;
  /** The realm sso session max lifespan remember me. */
  sso_session_max_lifespan_remember_me?: number;
  /** State of the realm. */
  state?: "present" | "absent";
  /** The realm supported locales. */
  supported_locales?: string | string[];
  /** Authentication token for Keycloak API. */
  token?: string;
  /** The realm user managed access allowed option. */
  user_managed_access_allowed?: boolean;
  /** Verify TLS certificates (do not disable this in production). */
  validate_certs?: boolean;
  /** The realm verify email option. */
  verify_email?: boolean;
  /** The realm wait increment in seconds. */
  wait_increment_seconds?: number;
  /** List of acceptable AAGUIDs for WebAuthn authenticators. */
  web_authn_policy_acceptable_aaguids?: string | string[];
  /** Attestation conveyance preference for WebAuthn. */
  web_authn_policy_attestation_conveyance_preference?: string;
  /** Authenticator attachment preference for WebAuthn authenticators. */
  web_authn_policy_authenticator_attachment?: string;
  /** Avoid registering the same authenticator multiple times. */
  web_authn_policy_avoid_same_authenticator_register?: boolean;
  /** Timeout for WebAuthn credential creation (ms). */
  web_authn_policy_create_timeout?: number;
  /** Additional acceptable origins for WebAuthn requests. */
  web_authn_policy_extra_origins?: string | string[];
  /** List of acceptable AAGUIDs for WebAuthn passwordless authenticators. */
  web_authn_policy_passwordless_acceptable_aaguids?: string | string[];
  /** Attestation conveyance preference for WebAuthn passwordless. */
  web_authn_policy_passwordless_attestation_conveyance_preference?: string;
  /** Authenticator attachment for WebAuthn passwordless. */
  web_authn_policy_passwordless_authenticator_attachment?: string;
  /** Avoid registering the same authenticator multiple times for passwordless. */
  web_authn_policy_passwordless_avoid_same_authenticator_register?: boolean;
  /** Timeout for WebAuthn passwordless credential creation (ms). */
  web_authn_policy_passwordless_create_timeout?: number;
  /** Additional acceptable origins for WebAuthn passwordless requests. */
  web_authn_policy_passwordless_extra_origins?: string | string[];
  /** Enable passkeys (conditional UI) authentication in the username forms. */
  web_authn_policy_passwordless_passkeys_enabled?: boolean;
  /** Whether resident keys are required for WebAuthn passwordless (V(Yes)/V(No)/V(not specified)). */
  web_authn_policy_passwordless_require_resident_key?: string;
  /** WebAuthn Passwordless Relying Party Entity Name. */
  web_authn_policy_passwordless_rp_entity_name?: string;
  /** WebAuthn Passwordless Relying Party ID (domain). */
  web_authn_policy_passwordless_rp_id?: string;
  /** List of acceptable WebAuthn signature algorithms for passwordless. */
  web_authn_policy_passwordless_signature_algorithms?: string | string[];
  /** User verification requirement for WebAuthn passwordless. */
  web_authn_policy_passwordless_user_verification_requirement?: string;
  /** Whether resident keys are required for WebAuthn (Yes/No/not specified). */
  web_authn_policy_require_resident_key?: string;
  /** WebAuthn Relying Party Entity Name. */
  web_authn_policy_rp_entity_name?: string;
  /** WebAuthn Relying Party ID (domain). Empty string means use request host. */
  web_authn_policy_rp_id?: string;
  /** List of acceptable WebAuthn signature algorithms. */
  web_authn_policy_signature_algorithms?: string | string[];
  /** User verification requirement for WebAuthn. */
  web_authn_policy_user_verification_requirement?: string;
}

export interface KeycloakRealmReturn {
  /** Representation of realm after module execution (sample is truncated). */
  end_state?: Record<string, unknown>;
  /** Representation of existing realm (sample is truncated). */
  existing?: Record<string, unknown>;
  /** Message as to what action was taken. */
  msg?: string;
  /** Representation of proposed realm. */
  proposed?: Record<string, unknown>;
}

export const keycloak_realm = defineModule<KeycloakRealmArgs, KeycloakRealmReturn>("community.general.keycloak_realm");
